// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    double randomNum = Math.random(); 
		int n = Integer.parseInt(args[0]);
		int x = 1;
		int t = 0;
		int r = 0;
		while (x <= n) { 
		    double randomNumi = Math.random(); 
			x = x+1;
			if (randomNumi> 0.5) {
				t= t+1;
				
			} else {
				r = r+1; 
			}
			

		} 
		
	System.out.println("> 0.5: " + t + " times" );
	System.out.println("< 0.5: " + r + " times" );
	if ( t>r && r>=0) {
	System.out.println("ratio:" + ((double)r/t));	
	} else if (t<r && t>0) {
	System.out.println("ratio:" + ((double)t/r));	
	}
	}
}
